export type TCommonWords = {
  login: string;
  email: string;
  password: string;
  darkMode: string;
  yes: string;
  lightMode: string;
  cancel: string;
  delete: string;
  confirmDelete: string;
  confirmDeleteMessage: string;
  save: string;
  signIn: string;
  dashboard: string;
  profile: string;
  home: string;
  workers:string;
  companies: string;
  logOut: string;
  name: string;
  lastName: string;
  emailUser: string;
  turn: string;
  schedules: string;
  code: string;
  date: string;
  start: string;
  end: string;
  schedulesOf: string;
  inTurn: string;
  outOfTurn: string;
  addCompany: string;
  companyInformation: string;
  companyName: string;
  companyCode: string;
  refreshList: string;
};
